### ISSUE TITLE
QUIC not support IPv6URL

### ISSUE THREAD

**Issue by iamsurfing** [folbricht/routedns#160]
`  [resolvers.google]`
`  address="https://[2001:4860:4860::8888]/dns-query{?dns}"`
`  protocol="doh"`
`  transport = "quic"`

Routedns say "too many colons in address".

**Comment by cbuijs** [comment]
Use "dns.google" as address and add the ip-address with:

bootstrap-address = "ipv6-address"

**Comment by folbricht** [comment]
The issue originates from https://github.com/lucas-clemente/quic-go/blob/master/client.go#L235-L246 The library tries to determine the SNI to use for the connection and first splits off the port which fails since it's an IP6 address without the `[..]` around it anymore. I need to look into how best to fix this.

**Comment by folbricht** [comment]
https://github.com/folbricht/routedns/pull/163 should fix this issue as a by-product. It also updates the library and improve its use. Feel free to give it a try.
