### ISSUE TITLE
100% CPU usage when using fastest and random groups together, with resolvers and bootstrap address pointing to a unreachable network address.

### ISSUE THREAD

**Issue by alpominth** [folbricht/routedns#332]
This is my config that I use in my Linux PCs, it points to a DNSCrypt instance and many DoH HTTP/3 resolvers using fastest and random group schemes: https://paste.ee/p/foKdg

The address "10.8.56.2" is of a VPN that starts automatically after RouteDNS using systemd.

The problem is that RouteDNS uses 100% of CPU until the address "10.8.56.2" is reachable. Sometimes I use my PC with network turned off and this have been an issue.

I was able to reproduce this behavior, and I realized that if the bootstrap address has the option `local-address` and the network IP is not existent, an infinite loop of queries of bootstrap address is made: https://paste.ee/r/4g6me/0

This problem is happening with [master](url) branch.

@folbricht 

I modified my config to run as normal user, I think you'll be able to reproduce the problem too: https://paste.ee/r/U3y4A/0

**Comment by folbricht** [comment]
Thanks. Was able to reproduce it. The issue was a bug that meant your `reset-after` time was being used in nanoseconds, not seconds. So failed resolvers would come back immediately, and so it would keep trying to resolve it. Try the `issue-332` branch

I should probably have an total number of failures as a limit before giving up. Maybe give up after 2 * number of resolvers in the group.

**Comment by alpominth** [comment]
Thanks, it was fixed: https://paste.ee/r/QV07b/0
