### ISSUE TITLE
Enhance "Blacklist" feature with FILE and/or URL option

### ISSUE THREAD

**Issue by cbuijs** [folbricht/routedns#4]
Hi,

How about enhancing the blacklist feature with a FILE and/or URL option to load blacklisted entries from file/or URL. When URL a "Refresh" timer needed to be added.

Also, maybe also enhance it with a "simple domain" convention besides the regex one to define blacklist entries. Especially for longer lists. Might consider to either the "simple domain" includes sub-domains, or do syntax ("*.domain.com") for it, or have a "also-subdomains" option (default true).

Syntax for the file/url would be one entry per line. Might consider "hosts" file format (it is used a lot in existing blacklists), but a regex or simple domain (as stated above) per line would be sufficient.

A mix and/or multiple file/url's should be allowed/work.

Hope I am not rambling too much here :-).

-Chris.

**Comment by folbricht** [comment]
Been considering implementing this already. Would probably add a new entity `file-blocklist` that supports file:// as well as http:// locations. Do you have some examples? Especially of the "hosts" format you mentioned.

**Comment by cbuijs** [comment]
Host format is just:

`<IP><WHITESPACE><DOMAIN>`

example:

`127.0.0.1 doubleclick.net`

For more examples:
https://github.com/cbuijs/accomplist/tree/master/deugniets (My stuff, also other formats)
https://github.com/StevenBlack/hosts
https://github.com/AdAway/AdAway/wiki/HostsSources
etc ...

You might want to consider to use the host format for blocking (use zero-ip 0.0.0.0 or/and ::) and/or spoofing (usablei/valid ip):

Would block entries:
```
0.0.0.0 doubleclick.net
:: block.me
```

Would spoof:
```
192.168.1.66 www.myspoof.nl
199.123.1.2 www.crapshoot.nl
2001:db8:123::1 www.ipv6.nl
```

etc ...

**Comment by folbricht** [comment]
Thanks for the explanation. I know the hosts file quite well, but didn't realize the same is used for blocklists like that. So I'm thinking of first extending the existing blocklist with simple domain strings, then later add another type for files and URLs that'll support the hosts file too.

**Comment by dnscrypt-ca** [comment]
If I may offer my three cents, I'd love to see this implemented as a regex or wildcard system, more like dnsmasq handles manual entries instead of hosts format.  An example of why would be intellitxt.com, a somewhat well known service for injecting annoying js popup ads.  They provide their services based on third level domains such as

`goofball.intellitxt.com`

If someone wanted to block these popups they would need hundreds or even thousands of entries in a hosts style block list but only a single line in a wildcard/regex style list.  Additionally, new entries would have to be appended to a hosts file list, whereas a wildcard/regex system would block any new third level domains without modification.

**Comment by folbricht** [comment]
Rexexp will definitely stay. Probably also going to support hosts-formatted lists since they appear to be quite popular. And all of those can be provided in local config, local files or from a remote location with configurable refresh interval.

What I'm not yet sure about is the support for simple domain lists with or without wildcards. Could be either one of these:
1) `*.some.domain.com` - It's not clear if that should match only subdomains or the domain itself as well. Also, couldn't allow any wildcards in the middle.
2) `some.domain.com` with a flag to make it match exact only or to include anything under it

Thoughts?

**Comment by dnscrypt-ca** [comment]
I would suggest:

- domain.com: blocks just domain.com and not subdomains
- .domain.com: blocks domain.com and all subdomains
- *.domain.com: blocks all subdomains but not domain.com

Does that sound reasonable? :-)

**Comment by folbricht** [comment]
https://github.com/folbricht/routedns/pull/7 implements the additional blocklist types, still local config only at this point, support for remote download or local files will come later.

**Comment by cbuijs** [comment]
Working great so far, the "file" version can be actually done by creating a separate toml file and include it from the prompt as per #6 .

**Comment by folbricht** [comment]
Reloading the config files isn't easily doable. It'll probably have to be a separate text file locally. Once HTTP is supported, adding other sources like local files etc is going to be trivial.

**Comment by folbricht** [comment]
The PR has been updated to support 3 types (domain, regexp, hosts) and 3 locations (plain in config, local file, http) with optional refresh. Should work but needs a bit of a cleanup and doc updates. Here's an example of a remote regex blocklist that gets reloaded daily.

```toml
[groups.cloudflare-blocklist]
type = "blocklist"
resolvers = ["cloudflare-dot"] # Anything that passes the filter is sent on to this resolver
format    = "regexp"           # "domain", "hosts" or "regexp", defaults to "regexp"
source    = "https://raw.githubusercontent.com/cbuijs/accomplist/master/deugniets/plain.black.regex.list"
refresh   = 86400              # Time to refresh the blocklist from the file in seconds
```

**Comment by cbuijs** [comment]
Working, I am not sure, I need to test the domain-syntax more when I find some more time, it seems that the `.domain.com` (with dot) and `domain.com` (without leading dot) functionality is reversed according how it is subscribed. Also... What takes precedence when both exist? I would suggest the non-dot version as it is more explicit?

**Comment by cbuijs** [comment]
Looks like the lists are not downloaded or loaded at start? There is no feedback in logging about loading/refreshing the lists and when doing queries it says:

`resolver="Blocklist(items=0)`

I didn't have time to look at the code yet, but the lists are not loading from url or file.

**Comment by folbricht** [comment]
Sorry, should have been more explicit. That code hasn't been merged to master yet, it's still on the branch (https://github.com/folbricht/routedns/tree/blocklist-formats). The message in your comment is from the old implementation on master.

**Comment by folbricht** [comment]
Docs updated, getting close to merging that PR. Wrt the priority when both, `domain.com` and `.domain.com` are present, the more general rule wins currently. That'd be the `.domain.com` one as it matches exactly and sub-domains.

**Comment by cbuijs** [comment]
Using the "blocklist-formats" version works great.

One small request, not a dealbreaker, but in the logging, could it be shown on which "regex", "domain" or "hosts" entry is hit?

And logging in general on the refresh and load of lists would be a great one.

**Comment by folbricht** [comment]
Thanks for checking it out. I can add some more logging. Showing the matching rule for "regexp" and "hosts" is easy, for "domain" it's more difficult since that one uses a different data structure internally for better performance. Will see what I can do there. The refresh/loading of remote lists is logged already.

**Comment by folbricht** [comment]
Added more logging and merged the PR. Let me know if anything's not working or missing.

**Comment by cbuijs** [comment]
Working like a charm.

**Comment by folbricht** [comment]
Thanks for checking it out.
